#!/usr/bin/env python

import argparse
import simplejson as json
import csv

parser = argparse.ArgumentParser(description='A script convert between different sequence feature formats' )
parser.add_argument('--input', help="An input feature file", type=argparse.FileType('r'), \
     required = True)
parser.add_argument('--output', help="A output feature file",type=argparse.FileType('w'), default='-')
parser.add_argument('--infmt', help ="Input format", choices=["csv"], default="csv") 
parser.add_argument('--outfmt', help ="Desired output format", choices=["esom-lrn"], default="esom-lrn") 
args = parser.parse_args()

def csv2esom(csvhandle, esomhandle):
    """Returns a writes an ESOM file from a csv"""
    elements = 0
    for i, line in enumerate(csvhandle):
        linelist =line.strip().split('\t')
        if len(linelist) > elements:
            elements = len(linelist)
    esomhandle.write("# ESOM .lrn file generated by GeneLearn " + "\n")
    esomhandle.write("% " +str(i+1) + "\n")
    esomhandle.write("% " + str(elements -1 ) + "\n")
    line4 = [ "9"] + ["1"]*(elements - 1)
    esomhandle.write("% " + ('\t'.join(map(str,line4)) + "\n"))
    names = []
    for j in range(elements-1):
        names.append("feat" + str(j+1))
    line5 = ["taxid"] + names
    esomhandle.write("% " + ('\t'.join(map(str,line5)) + "\n"))
    csvhandle.seek(0,0)
    for vector in csvhandle:
        esomhandle.write("% " + vector.strip() + "\n")


if args.infmt == "csv" and args.outfmt == "esom-lrn":
    csv2esom(args.input,args.output)
    args.input.close()
    args.output.close()
    
else:
    args.input.close()
    args.output.close()
    raise ValueError('Only csv to esom .lrn conversion is supported at this time') 