#!/bin/bash
# Set SGE options:
## ensure a specific environment variable is set properly
#$ -v env_var=<value>
## run the job in the current working directory (where qsub is called)
#$ -cwd
## specify an email address
#$ -M qingpeng@lbl.gov
## specify when to send the email when job is (a)borted, (b)egins or (e)nds normally
#$ -m abe
## Specify a run time of 11 hours (or 39600 seconds)
#$ -l h_rt=3:00:00
## Specify 12G of memory for the job
#$ -l ram.c=80G
#$ -q high.q

## Your job info goes here
/global/homes/q/qpzhang/anaconda/bin/python /global/homes/q/qpzhang/Github/jgi-ViCA/scripts/sklearn_training_model.py /global/projectb/scratch/qpzhang/Run_Genelearn/Full_nextflow/all_segment.fasta.vect.euk_and_non_euk.svmlib.0_1 /global/projectb/scratch/qpzhang/Run_Genelearn/Full_nextflow/all_segment.fasta.vect.euk_and_non_euk.svmlib.0_1.model /global/projectb/scratch/qpzhang/Run_Genelearn/Full_nextflow/all_segment.fasta.vect.euk_and_non_euk.svmlib.0_1.scaler True

