+--------------+-----------------+--------+
| target_label | predicted_label | count  |
+--------------+-----------------+--------+
|   Bacteria   |    ssRNAPhage   |  104   |
|   Bacteria   |    ssDNAVirus   |  5486  |
|  dsDNAVirus  |    ssDNAVirus   |  1141  |
|  dsDNAVirus  |     Bacteria    |  799   |
| Retroviruses |   Retroviruses  |  2127  |
|  ssRNAVirus  |     Bacteria    |  108   |
|   Archaea    |    dsDNAPhage   |   11   |
|   Bacteria   |    dsRNAVirus   | 15799  |
|  dsRNAVirus  |    dsRNAVirus   |  1215  |
|  ssRNAVirus  |    dsRNAVirus   |  756   |
|  dsDNAPhage  |    ssDNAVirus   |  4751  |
|  dsDNAPhage  |     Bacteria    |  8174  |
|  ssRNAVirus  |   Retroviruses  |  343   |
|  dsDNAVirus  |    ssRNAVirus   |  1336  |
|   Archaea    |   Retroviruses  |  212   |
|  ssDNAVirus  |    dsRNAVirus   |   2    |
|   Archaea    |    dsRNAVirus   |  568   |
|  ssDNAPhage  |     Bacteria    |   71   |
| Retroviruses |    dsDNAVirus   |   69   |
|   Archaea    |    dsDNAVirus   |  237   |
|   Bacteria   |    dsDNAVirus   |  7368  |
|   Bacteria   |   Retroviruses  |  4166  |
|  ssRNAVirus  |    ssDNAPhage   |   26   |
|   Archaea    |    ssDNAVirus   |  342   |
|  dsRNAVirus  |    ssRNAVirus   |  198   |
|  dsRNAPhage  |    dsRNAVirus   |   53   |
|  dsDNAVirus  |    dsDNAVirus   | 11452  |
|  ssDNAPhage  |    ssDNAPhage   |  1164  |
|  dsDNAVirus  |    dsDNAPhage   |  122   |
|  dsDNAPhage  |     Archaea     |  6560  |
| Retroviruses |    dsRNAVirus   |   3    |
| Retroviruses |    ssDNAVirus   |   38   |
|  dsRNAVirus  |   Retroviruses  |   10   |
|   Archaea    |     Archaea     | 16441  |
|  ssDNAVirus  |    ssDNAVirus   |  2705  |
|  dsDNAVirus  |    ssRNAPhage   |   7    |
|   Archaea    |    dsRNAPhage   |   1    |
|  dsDNAPhage  |    dsDNAPhage   |  7368  |
|  ssRNAVirus  |    ssRNAVirus   |  6770  |
|   Archaea    |    ssRNAPhage   |   13   |
|  dsDNAPhage  |    ssRNAPhage   |  197   |
|  dsRNAPhage  |    dsRNAPhage   |  147   |
|  dsRNAVirus  |    dsDNAVirus   |   6    |
|   Bacteria   |    ssRNAVirus   |  3093  |
|  dsDNAVirus  |    dsRNAPhage   |   62   |
|  dsDNAPhage  |    dsRNAVirus   |  4547  |
|  dsDNAPhage  |    dsRNAPhage   |  435   |
|  ssRNAVirus  |    dsDNAVirus   |  932   |
|  ssDNAVirus  |    dsDNAVirus   |  135   |
|  dsDNAPhage  |   Retroviruses  |  1118  |
|   Bacteria   |    dsDNAPhage   |  3469  |
|  dsDNAPhage  |    ssDNAPhage   |  9488  |
|  dsRNAVirus  |    ssDNAVirus   |   9    |
|   Archaea    |    ssDNAPhage   |  202   |
|  dsDNAPhage  |    dsDNAVirus   |  736   |
|  dsDNAVirus  |     Archaea     |  1362  |
|   Archaea    |    ssRNAVirus   |  472   |
|  dsDNAVirus  |    dsRNAVirus   |  516   |
|   Bacteria   |    dsRNAPhage   |  1285  |
|  dsDNAPhage  |    ssRNAVirus   |  1245  |
|   Archaea    |     Bacteria    |  799   |
|   Bacteria   |    ssDNAPhage   | 52617  |
|  ssRNAVirus  |    ssDNAVirus   |  706   |
|  dsDNAVirus  |    ssDNAPhage   |  976   |
|   Bacteria   |     Bacteria    | 823819 |
|  dsDNAVirus  |   Retroviruses  |  176   |
|  ssRNAVirus  |     Archaea     |   72   |
|   Bacteria   |     Archaea     | 77131  |
